sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .l

script:
  -  docker run docker-react npm run test -- --coverage

deploy:
  provider: elaticbeanstak
  region: us-west-2
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elaticbeanstak-us-west-2-<id>"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
