FROM node:alpine
WORKDIR '/app'

COPY package.json .

ENV http_proxy http://172.17.0.1:3128 
ENV https_proxy http://172.17.0.1:3128 
#RUN npm install
RUN npm config set proxy http://172.17.0.1:3128 install
COPY . .

CMD ["npm", "run", "start"]